#!/usr/bin/with-contenv bash

# Determine if setup is needed
if ! command -v git; then
## Ubuntu
    if [ -f /usr/bin/apt ]; then
        apt-get install --no-install-recommends -y \
            git
    fi
    # Alpine
    if [ -f /sbin/apk ]; then
        apk add --no-cache \
            git
    fi
fi

# Define Git Config
if [ ! -z "$GIT_EMAIL" ]; then
    git config --global user.email "$GIT_EMAIL"
fi

if [ ! -z "$GIT_USERNAME" ]; then
    git config --global user.name "$GIT_USERNAME"
fi